### ISSUE TITLE
[Android] Display Device Information When Selected

### ISSUE THREAD

**Issue by zakuArbor** [zakuArbor/proxyAuth#51]
**Epic:** #50 
**Description:** When the user selects the device, they'll be redirected to either a fragment or an activity where they'll have the device overview where they can:
* see the name of the device
* the address of the device
* Is it currently authenticating a device
* revoke trust
* Start/Stop authenticating a device

**Tasks**
- [x] When a device is selected, a new activity/fragment
- [x] The new activity/fragment will contain placeholder values (i.e. display name, address, is the device being authenticated, and a toggle)
- [x] Have the toggle button change color depending on if the connection is on or off

**Note:** This activity/fragment in future iterations will not be the default behavior when they select the device. The end goal is to have this activity/fragment only appear when the user selects a gearbox (i.e. settings) similar to how it is on the Android Bluetooth.

**Summary:**
* 6bd30ce already completes the UI to view the device information (with non-real values). #58 deals with the backend.
