### ISSUE TITLE
Add Doxygen (Documentation Generator) Support

### ISSUE THREAD

**Issue by zakuArbor** [zakuArbor/proxyAuth#54]
## Purpose
Replace existing function comments with Doxygen-style comments so that I can generate code documentation.

## Tasks/Goals
- [ ] Install Doxygen on a personal machine
- [ ] Replace a single header file with Doxygen-style comments
- [ ] Change all header files to comply with Doxygen-style comments
- [ ] Update Makefile to have an option to generate Doxygen
- [ ] Create Github Action to generate Documents whenever a header file is updated

## Summary
*To fill out once the issue is to be closed. Give a short summary of the changes you made to implement or fix an issue*

**Comment by zakuArbor** [comment]
**Requirements:**
* flex
* bison
