### ISSUE TITLE
[Android] Get Bluetooth Device Information

### ISSUE THREAD

**Issue by zakuArbor** [zakuArbor/proxyAuth#58]
## Purpose
Display device information from the Bluetooth manager. #51 deals with the frontend but this task deals with the backend

## Tasks/Goals
- [ ] Send data to the new activity/fragment
- [ ] Use data binding rather than findviewbyid (refer to this [page](https://classroom.udacity.com/courses/ud9012/lessons/4f6d781c-3803-4cb9-b08b-8b5bcc318d1c/concepts/a39e5191-f206-43a4-b293-3f1d6f6a6549))
- [ ] Toggle is set to ON automatically once Bluetooth connection is established
- [ ] Toggle OFF will exit the fragment/activity and goes back to the default device

## Summary
*To fill out once the issue is to be closed. Give a short summary of the changes you made to implement or fix an issue*
