### ISSUE TITLE
[SECURITY] Writing Pass Buffersize

### ISSUE THREAD

**Issue by zakuArbor** [zakuArbor/proxyAuth#71]
## Purpose
* Static Analyzer triggered a buffer overflow warning 
* Note: I believe security bugs like these are not supposed to be public but I am not aware of anyone using the project
* A good example of static analyzers catching bugs in the code

## Tasks/Goals
- [x] Replace `strncpy` size parameter with the minimum of either the length of the string or the size of the buffer
- [x] Ensure no writes are done pass the buffer size (i.e. `buf[SIZE - 1]` instead of `buf[SIZE]`
- [x] use `assert` to ensure program does not exceed a certain length

## Summary
*To fill out once the issue is to be closed. Give a short summary of the changes you made to implement or fix an issue*

**Comment by zakuArbor** [comment]
![proxyauth-vul-1](https://user-images.githubusercontent.com/17998930/153729002-5d9f5f5a-86b8-4900-b52e-d8495d1faac2.png)
